public static class SoaringKeys
{
	public const string Error_BadRequesMessage = "{ \"error_message\" : \"Failed to generate connection request\"}";

	public const string Error_NotInitializedMessage = "Soaring Is Not Initializes";

	public const string Soaring_ErrorMessageKeys = "error_message";

	public const string Soaring_ErrorCodeKeys = "error_code";

	public const string Soaring_ActionKey = "action";

	public const string Modules_Handshake_GetKeys_Key = "handshake_pt1";

	public const string Modules_Handshake_TestKeys_Key = "handshake_pt2";

	public const string Modules_Handshake_FinishKeys_Key = "handshake_pt3";

	public const string Modules_LoginUserKey = "loginUser";

	public const string Modules_LookupUserKey = "lookupUser";

	public const string Modules_RegisterUserKey = "registerUser";

	public const string Modules_GenerateUserKey = "retrieveNextAutogeneratedUserTag";

	public const string Modules_UpdateProfileKey = "updateUserProfile";

	public const string Modules_GenerateInviteKey = "retrieveInvitationCode";

	public const string Modules_AdServerKey = "adServer";

	public const string Modules_RegisterDevice = "registerDevice";

	public const string Modules_RetrieveUserProfile = "retrieveUserProfile";

	public const string Modules_UpdateUserProfileKey = "updateUserProfile";

	public const string Modules_ApplyInviteCodeKey = "applyInvitationCode";

	public const string Modules_SearchFriendKey = "searchUsers";

	public const string Modules_RequestFriendKey = "requestFriendship";

	public const string Modules_RemoveFriendKey = "removeFriendship";

	public const string Modules_SendSessionDataKey = "saveGameSession";

	public const string Modules_RetrieveSessionDataKey = "retrieveGameSession";

	public const string Modules_RetrieveFriendListKey = "retrieveFriendsList";

	public const string Modules_CheckRewardsKey = "retrieveVirtualGoodCoupons";

	public const string Modules_RedeemRewardsKey = "tearVirtualGoodCoupons";

	public const string Modules_ServerTimeKey = "retrieveServerTime";

	public const string Modules_VerifyRecieptKey = "validateIapReceipt";

	public const string Modules_RetrievePurchasesKey = "retrieveIapPurchases";

	public const string Modules_SendMessagesKey = "sendMessage";

	public const string Modules_RetrieveMessagesKey = "retrieveUnreadMessages";

	public const string Modules_MarkMessageReadKey = "markMessagesAsRead";

	public const string Modules_ResetUserPasswordKey = "resetUserPassword";

	public const string Modules_RenewUserPasswordKey = "renewUserPassword";

	public const string Modules_RequestFriendWithTagKey = "requestFriendshipWithTag";

	public const string Modules_RemoveFriendWithTagKey = "removeFriendshipWithTag";

	public const string Modules_RetrieveAddressesKey = "retrieveGameLinks";

	public const string Modules_RetrieveVersionsKey = "retrieveVersions";

	public const string Modules_DownloadFileKey = "downloadFiles";

	public const string Modules_ChangeUserPasswordKey = "changeUserPassword";

	public const string Modules_RetrieveProductsKey = "retrieveIapProducts";

	public const string Modules_SaveStatKey = "saveStat";

	public const string Modules_SaveAnonymousStatKey = "saveAnonymousStat";

	public const string Modules_RetrieveABCampaignKey = "retrieveABCampaignData";

	public const string Modules_FireEventKey = "fireEvent";

	public const string Soaring_UserAuthTokenKey = "authToken";

	public const string Soaring_GameCenterIDKey = "gamecenterId";

	public const string Soaring_AmazonIDKey = "amazonId";

	public const string Soaring_GoogleIDKey = "googleId";

	public const string Soaring_FacebookIDKey = "facebookId";

	public const string Soaring_LoginTypeKey = "loginType";

	public const string Soaring_DeviceIDKey = "deviceId";

	public const string Soaring_NameKey = "name";

	public const string Soaring_UserTagKey = "tag";

	public const string Soaring_UserIDKey = "userId";

	public const string Soaring_UserPasswordKey = "password";

	public const string Soaring_UserAutoCreated = "autoCreated";

	public const string Soaring_UserEmailKey = "email";

	public const string Soaring_UserEmailsKey = "emails";

	public const string Soaring_GameIDKey = "gameId";

	public const string Soaring_UserStatusKey = "status";

	public const string Soaring_InvitationCodeKey = "invitationCode";

	public const string Soaring_ResetTokenKey = "resetToken";

	public const string Soaring_OldPasswordKey = "oldPassword";

	public const string Soaring_NewPasswordKey = "newPassword";

	public const string Soaring_ScoreKey = "score";

	public const string Soaring_PictureUrlKey = "pictureUrl";

	public const string Soaring_IconKey = "icon";

	public const string Soaring_SessionTypeKey = "sessionType";

	public const string Soaring_QueryTypeKey = "queryType";

	public const string Soaring_CustomKey = "custom";

	public const string Soaring_PublicKey = "public";

	public const string Soaring_PrivateKey = "private";

	public const string Soaring_QueryKey = "query";

	public const string Soaring_CouponKey = "coupons";

	public const string Soaring_SortKey = "sort";

	public const string Soaring_TypeKey = "type";

	public const string Soaring_ValueKey = "value";

	public const string Soaring_MessagesKey = "messages";

	public const string Soaring_DataKey = "data";

	public const string Soaring_TimestampKey = "timestamp";

	public const string Soaring_DateTimeKey = "datetime";

	public const string Soaring_GameSessionIdKey = "gameSessionId";

	public const string Soaring_IdentifiersKey = "identifiers";

	public const string Soaring_TokenKey = "token";

	public const string Soaring_ProtocolKey = "protocol";

	public const string Soaring_PlatformKey = "platform";

	public const string Soaring_ProductIDKey = "productId";

	public const string Soaring_RecieptKey = "receipt";

	public const string Soaring_LabelKey = "label";

	public const string Soaring_InternalKey = "SCInternal";

	public const string Transport_PostKey = "tposts";

	public const string Transport_GetKey = "tgets";

	public const string Transport_UrlKey = "turl";

	public const string Transport_SaveKey = "tsave";

	public const string Transport_ChannelKey = "tchannel";

	public const string Transport_ObjectKey = "tobject";

	public const string Transport_CallbackKey = "tcallback";

	public const string Transport_VerifyCallbackKey = "tvcallback";

	public const string Transport_ContextKey = "tcontext";

	public const string Transport_TokenKey = "trToken";

	public const string Transport_IgnoreOffline = "trIOff";

	public const string Transport_InternalRegister = "tregister";

	public const string SoaringSort_Descending = "descending";

	public const string SoaringSort_Ascending = "ascending";

	public const string Soaring_GUIDKey = "guid";

	public const string Soaring_DeviceGUIDKey = "device_seq_id";

	public const string Soaring_DeviceSequenceIDKey = "device_seq_num";

	public const string Soaring_EventNameKey = "event_name";

	public const string Soaring_EventTimeKey = "event_time";

	public const string Soaring_OSVersionKey = "os_version";

	public const string Soaring_OfflineKey = "Offline";
}
